#!/bin/bash
ver="rustc --version"
command="./bin/RsHelloPrime"

arg1=${1:-100000}
arg2=${2:-1000}
shift 2
m=0; t=1; r=1
while getopts ":t:m:r:" opt; do
  case $opt in
    t) t=$OPTARG ;;
    m) m=$OPTARG ;;
    r) r=$OPTARG ;;
  esac
done

if [[ $arg1 == e* ]]; then arg1="1$arg1"; fi
if [[ $arg2 == e* ]]; then arg2="1$arg2"; fi

limit=$(printf "%.0f" "$arg1")
page=$(printf "%.0f" "$arg2")

command="$command $limit $page $m $t"

echo "Display the version information : "
eval "$ver"

echo "Run the command : $command"
for ((i=0; i<r; i++)); do eval "$command"; done